### ISSUE TITLE
$emailLinkRegex doesn't copy correctly from raw

### ISSUE THREAD

**Issue by mortenya** [gfoss/PSRecon#3]
I copied the script from raw and line 1010: $emailLinkRegex had unknown characters around the pattern string.

On PowerShell v4 that variable will generate parse errors unless it's wrapped in quotes: "([a-zA-Z]{3,})://([\w-]+\.)+[\w-]+(/[\w- ./?%&=]*)*?"

Looking at it in the ACE editor it doesn't show any quotes around the string.

**Comment by gfoss** [comment]
Good catch! I wrote the script to v2, so didn't know about the issue in v4.
I need to fix another issue with that regex anyways, so I'll go ahead and
take care of both when I have some free time.

Thanks!

**Comment by mortenya** [comment]
Awesome, and thanks for publishing that script.

I've wrestled with taking scripts written in v4 back to v2, and those minor differences always cause headaches.

**Comment by gfoss** [comment]
No problem, thanks for testing it out!

I've resolved this issue, fixed the link regex, and made a few other small changes.
